import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getFirestore,doc,getDoc,collection,getDocs} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';
import {defaults,defaultProducts,waLink,safeUrl,money} from './site-data.js';
const root=document.getElementById('public-root'),prefix=new URL('.',import.meta.url).pathname,href=(path='')=>prefix+path;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const maybeImage=s=>{if(typeof s!=='string')return '';if(/^https:\/\/drive\.google\.com\/thumbnail\?id=[A-Za-z0-9_-]{10,}(&sz=w[0-9]{2,4})?$/.test(s))return s;return /^data:image\/(webp|jpeg|png);base64,[a-zA-Z0-9+/=]+$/.test(s)&&s.length<750000?s:''};
const image=(url,alt,cls='photo')=>url?`<img class="${cls}" alt="${esc(alt)}" loading="lazy" src="${esc(url)}">`:`<div role="img" aria-label="Foto ${esc(alt)} belum tersedia" class="${cls} placeholder">🥚</div>`;
let cfg=structuredClone(defaults),products=structuredClone(defaultProducts),gallery=[],page='beranda',productId='',primary=null,galleryVisible=6;
const publicMeta=(p)=>cfg.seo?.[p]||defaults.seo[p]||defaults.seo.produk;
function pathPage(){const p=location.pathname.substring(prefix.length).replace(/^\/+|\/+$/g,'').split('/').filter(Boolean);if(p[0]==='produk'&&p[1]){page='detail';productId=p[1];}else if(['produk','galeri','profil','kontak'].includes(p[0]))page=p[0];else page='beranda';if(page==='produk'&&new URLSearchParams(location.search).has('item')){page='detail';productId=new URLSearchParams(location.search).get('item')||''}}
function urlProduct(p){return ['horn','omega'].includes(p.id)?href('produk/'+p.id+'/'):href('produk/?item='+encodeURIComponent(p.id))}
function primaryLink(item=''){if(!primary)return '';return waLink(primary.number,`Halo ${cfg.name}, saya ingin menanyakan informasi${item?' '+item:''}.`)}
function waIcon(){return `<img class="wa-icon" src="${href('assets/whatsapp.png')}" alt="" aria-hidden="true">`}
function linkButton(label,url,css='btn btn-green'){const ico=url?.startsWith('https://wa.me/')?waIcon():'';return url?`<a class="${css}" href="${esc(url)}" ${url.startsWith('https://wa.me/')?'target="_blank" rel="noopener noreferrer"':''}>${ico}${esc(label)}</a>`:`<span class="${css}" aria-disabled="true" title="Nomor WhatsApp belum diisi">${esc(label)}</span>`}
function header(){const names=cfg.nav?.length===5?cfg.nav:defaults.nav;const links=['','produk/','galeri/','profil/','kontak/'];const keys=['beranda','produk','galeri','profil','kontak'];return `<header class="header"><div class="wrap head"><a class="brand" href="${href()}" aria-label="Cangkang Mas, kembali ke Beranda">${image(maybeImage(cfg.logoImage)||href('assets/logo-header.png'),'Logo Cangkang Mas','brand-logo')}${cfg.showHeaderSlogan?`<small class="brand-slogan">${esc(cfg.slogan)}</small>`:''}</a><nav class="nav" id="mainNav" aria-label="Navigasi utama">${names.map((n,i)=>`<a href="${href(links[i])}" class="${page===keys[i]||page==='detail'&&i===1?'active':''}">${esc(n)}</a>`).join('')}</nav><button type="button" class="menu-toggle" id="menuButton" aria-label="Buka navigasi" aria-expanded="false">☰</button></div></header>`}
function footer(){const n=cfg.nav?.length===5?cfg.nav:defaults.nav;return `<footer class="footer"><div class="footer-title">${esc(cfg.name)}</div><p>${esc(cfg.slogan)}</p><p>${esc(cfg.copyright)}</p><nav aria-label="Navigasi footer">${n.map((v,i)=>`<${i?'span':'span'}>${i?'· ':''}<a href="${href(['','produk/','galeri/','profil/','kontak/'][i])}">${esc(v)}</a></span>`).join('')}<span>· <a href="${href('manajemen/')}">${esc(cfg.loginLabel||'Login')}</a></span></nav></footer>`}
function card(p,compact=false){const out=p.status==='out',l=primaryLink(p.name),productUrl=urlProduct(p);return `<article class="card">${image(maybeImage(p.image),p.name)}<div class="card-body"><div style="display:flex;gap:8px;justify-content:space-between;align-items:center;flex-wrap:wrap"><h3>${esc(p.name)}</h3><span class="badge ${out?'out':''}">${out?'Habis':'Tersedia'}</span></div><p>${esc(p.description)}</p>${compact?`<a class="btn btn-light" href="${productUrl}">${esc(cfg.buttons?.products||'Lihat Produk')} →</a>`:`<div class="prices"><div class="price"><small>HARGA ECERAN</small><strong>${money(p.retail)}</strong><small>per kg</small></div><div class="price"><small>HARGA GROSIR</small><strong>${money(p.wholesale)}</strong><small>per kg</small></div></div>${p.showMin&&p.minWholesale?`<p class="muted">Minimum grosir: ${esc(p.minWholesale)} kg</p>`:''}${out?'<p class="notice">Stok sedang tidak tersedia. Hubungi kami untuk menanyakan ketersediaan.</p>':''}<div class="buttons">${linkButton(out?'Tanya Ketersediaan':(cfg.buttons?.productAsk||'Tanya')+' '+p.name,l)}<a class="btn btn-light share" href="${productUrl}" data-share="${esc(productUrl)}" aria-label="Bagikan ${esc(p.name)}">↗ ${esc(cfg.buttons?.share||'Bagikan')}</a></div><p><a href="${productUrl}">Lihat detail ${esc(p.name)} →</a></p>`}</div></article>`}
function home(){const intro=products.filter(x=>x.visible!==false).slice(0,4);return `<section class="hero"><div class="wrap hero-layout">${image(maybeImage(cfg.heroImage),'Foto utama Cangkang Mas','hero-picture')}<div class="hero-copy"><span class="eyebrow">${esc(cfg.heroEyebrow)}</span><h1>${esc(cfg.heroTitle)}</h1><p>${esc(cfg.heroText)}</p><div class="buttons">${linkButton(cfg.buttons?.whatsapp||'Hubungi WhatsApp',primaryLink())}<a href="${href('produk/')}" class="btn btn-outline">${esc(cfg.buttons?.products||'Lihat Produk')} →</a></div></div></div></section><main><section class="section wrap"><div class="intro"><span class="overline">PRODUK KAMI</span><h2>${esc(cfg.homeProductTitle)}</h2><p>${esc(cfg.homeProductIntro)}</p></div><div class="grid">${intro.map(p=>card(p,true)).join('')||'<p>Produk segera tersedia.</p>'}</div></section><section class="section wrap"><div class="intro"><h2>${esc(cfg.serviceTitle)}</h2></div><div class="service-grid">${(cfg.services||[]).map(s=>`<div class="service"><b>✓ ${esc(s.title)}</b><p>${esc(s.text)}</p></div>`).join('')}</div></section></main>`}
function catalog(){return `<main class="section wrap"><div class="intro"><span class="overline">KATALOG PRODUK</span><h1>${esc(cfg.productTitle)}</h1><p>${esc(cfg.productIntro)}</p></div><div class="grid">${products.filter(p=>p.visible!==false).map(p=>card(p)).join('')||'<p>Belum ada produk yang ditampilkan.</p>'}</div><p class="notice" style="margin-top:22px">${esc(cfg.productNote)}</p></main>`}
function detail(){const p=products.find(p=>p.id===productId&&p.visible!==false);if(!p){document.title='Produk tidak ditemukan | Cangkang Mas';return `<main class="section wrap"><h1>Produk tidak ditemukan</h1><a href="${href('produk/')}">Kembali ke katalog</a></main>`;}document.title=p.seoTitle||p.name+' | Cangkang Mas';document.querySelector('meta[name="description"]')?.setAttribute('content',p.seoDescription||p.description);return `<main class="section wrap"><div class="detail"><a href="${href('produk/')}">← Kembali ke Produk</a><div style="margin-top:15px">${card(p)}</div></div></main>`}
function visibleGallery(){return gallery.filter(x=>x.visible!==false)}
function galleryPage(){const items=visibleGallery();return `<main class="section wrap"><div class="intro"><span class="overline">GALERI USAHA</span><h1>${esc(cfg.galleryTitle)}</h1><p>${esc(cfg.galleryIntro)}</p></div><div class="gallery-grid">${items.slice(0,galleryVisible).map((g,i)=>`<figure class="gallery-item" style="--focus-x:${Math.max(0,Math.min(100,Number(g.focusX??50)||0))}%;--focus-y:${Math.max(0,Math.min(100,Number(g.focusY??50)||0))}%"><button type="button" class="gallery-open" data-gallery="${i}" aria-label="Perbesar ${esc(g.title)}">${image(maybeImage(g.image),g.title,'gallery-thumb')}<span class="gallery-zoom" aria-hidden="true">⌕</span></button><figcaption>${esc(g.title)}${g.description?`<small>${esc(g.description)}</small>`:''}</figcaption></figure>`).join('')||'<p>Foto galeri belum diunggah.</p>'}</div>${items.length>galleryVisible?`<div class="gallery-more"><button type="button" class="btn btn-light" id="galleryMore">Lihat Foto Lainnya (${items.length-galleryVisible})</button></div>`:''}</main>`}
function profilePage(){return `<main class="section wrap"><div class="profile-layout">${image(maybeImage(cfg.profileImage),'Foto usaha Cangkang Mas')}<div><span class="overline">TENTANG KAMI</span><h1 style="color:var(--dark)">${esc(cfg.profileTitle)}</h1><p>${esc(cfg.profileText)}</p><div class="notice"><h3>${esc(cfg.profileHighlightTitle)}</h3>${esc(cfg.profileHighlightText)}</div><div class="buttons">${linkButton(cfg.buttons?.whatsapp||'Hubungi WhatsApp',primaryLink())}</div></div></div></main>`}
function locationEmbed(){const u=safeUrl(cfg.mapsUrl),a=(cfg.address||'').trim();if(u){try{const parsed=new URL(u);if((parsed.hostname==='www.google.com'||parsed.hostname==='google.com')&&parsed.pathname.startsWith('/maps/embed'))return u;if((parsed.hostname==='www.google.com'||parsed.hostname==='google.com')&&parsed.pathname.startsWith('/maps')&&parsed.searchParams.get('q'))return 'https://www.google.com/maps?q='+encodeURIComponent(parsed.searchParams.get('q'))+'&output=embed';}catch{}}return a?'https://www.google.com/maps?q='+encodeURIComponent(a)+'&output=embed':''}
function contactPage(){const all=(cfg.contacts||[]).filter(c=>c.active!==false&&c.number);const sorted=[...all].sort((a,b)=>Number(!!b.primary)-Number(!!a.primary));const mapUrl=safeUrl(cfg.mapsUrl),embed=locationEmbed();return `<main class="section wrap"><div class="intro"><span class="overline">KONTAK KAMI</span><h1>${esc(cfg.contactTitle)}</h1><p>${esc(cfg.contactIntro)}</p></div><div class="contact-list">${sorted.map(c=>`<div class="info"><h3>${waIcon()} ${esc(c.name)} ${c.primary?'<span class="badge">Prioritas</span>':''}</h3>${linkButton('Chat WhatsApp',waLink(c.number,`Halo ${cfg.name}, saya ingin menanyakan informasi telur.`))}</div>`).join('')||'<p>Nomor WhatsApp belum tersedia.</p>'}</div><div class="info" style="margin-top:18px"><h3>⌖ ${esc(cfg.locationTitle)}</h3><p>${esc(cfg.address||'Alamat belum dicantumkan.')}</p><p>Wilayah layanan: ${esc(cfg.region)}</p><p>Jam operasional: ${esc(cfg.hours||'Hubungi kami untuk informasi jam operasional.')}</p>${embed?`<iframe class="map" title="Peta lokasi Cangkang Mas" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="${esc(embed)}"></iframe>`:'<div class="notice">Isi alamat lengkap atau URL embed Google Maps melalui pengaturan Kontak agar pratinjau peta muncul di sini.</div>'}</div></main>`}
function updateSeo(){const k=page==='detail'?'produk':page,m=publicMeta(k);if(page!=='detail'){document.title=m.title||document.title;document.querySelector('meta[name="description"]')?.setAttribute('content',m.description||'')}if(m.index===false){let n=document.querySelector('meta[name="robots"]');if(!n){n=document.createElement('meta');n.name='robots';document.head.append(n)}n.content='noindex,follow'}}
function render(){primary=(cfg.contacts||[]).find(c=>c.primary&&c.active!==false&&c.number)||null;pathPage();updateSeo();root.innerHTML=header()+({beranda:home,produk:catalog,galeri:galleryPage,profil:profilePage,kontak:contactPage,detail} [page]||home)()+footer()+(primary?`<a class="float-wa" href="${esc(primaryLink())}" target="_blank" rel="noopener noreferrer" aria-label="Chat WhatsApp utama">${waIcon()}</a>`:'')+'<div id="site-message" role="status"></div>';
 document.getElementById('menuButton')?.addEventListener('click',e=>{const n=document.getElementById('mainNav');const expanded=n.classList.toggle('expanded');e.currentTarget.setAttribute('aria-expanded',String(expanded))});
 root.querySelectorAll('[data-share]').forEach(b=>b.addEventListener('click',async e=>{e.preventDefault();const u=new URL(b.getAttribute('data-share'),location.origin).href;try{if(navigator.share)await navigator.share({title:document.title,url:u});else{await navigator.clipboard.writeText(u);document.getElementById('site-message').textContent='Tautan produk disalin.'}}catch(err){if(err.name!=='AbortError')document.getElementById('site-message').textContent='Tidak dapat membagikan tautan.'}}));
 document.getElementById('galleryMore')?.addEventListener('click',()=>{galleryVisible+=6;render()});
 root.querySelectorAll('[data-gallery]').forEach(b=>b.addEventListener('click',()=>openGallery(Number(b.dataset.gallery))));}
function openGallery(index){const items=visibleGallery().filter(x=>maybeImage(x.image));const selected=visibleGallery()[index];const current=items.findIndex(x=>x.id===selected?.id);if(current<0)return;let at=current;const modal=document.createElement('div');modal.className='lightbox';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label','Foto galeri ukuran besar');const previousFocus=document.activeElement;
 const close=()=>{document.removeEventListener('keydown',keydown);modal.remove();previousFocus?.focus?.()};
 const show=()=>{const g=items[at];modal.innerHTML=`<button class="lightbox-arrow" type="button" data-prev aria-label="Foto sebelumnya">❮</button><figure><img alt="${esc(g.title)}" src="${esc(maybeImage(g.image))}"><figcaption>${esc(g.title)} <small>${at+1} / ${items.length}</small></figcaption></figure><button class="lightbox-arrow" type="button" data-next aria-label="Foto berikutnya">❯</button>`;modal.querySelector('[data-prev]').onclick=()=>{at=(at+items.length-1)%items.length;show()};modal.querySelector('[data-next]').onclick=()=>{at=(at+1)%items.length;show()};modal.querySelector('[data-prev]').focus()};
 const keydown=e=>{if(e.key==='Escape')close();if(e.key==='ArrowLeft'){e.preventDefault();at=(at+items.length-1)%items.length;show()}if(e.key==='ArrowRight'){e.preventDefault();at=(at+1)%items.length;show()}};
 let touchX=null;modal.addEventListener('touchstart',e=>{touchX=e.touches[0]?.clientX??null},{passive:true});modal.addEventListener('touchend',e=>{if(touchX===null)return;const change=(e.changedTouches[0]?.clientX??touchX)-touchX;touchX=null;if(Math.abs(change)>55){at=(at+(change<0?1:items.length-1))%items.length;show()}},{passive:true});modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',keydown);root.append(modal);show();}

async function load(){try{const db=getFirestore(initializeApp(firebaseConfig));const [configSnap,prodSnap,gallerySnap]=await Promise.all([getDoc(doc(db,'publicSite','config')),getDocs(collection(db,'publicSite','products','items')),getDocs(collection(db,'publicSite','gallery','items'))]);if(configSnap.exists())cfg={...defaults,...configSnap.data(),seo:{...defaults.seo,...configSnap.data().seo}};if(!prodSnap.empty)products=prodSnap.docs.map(d=>({...d.data(),id:d.id})).sort((a,b)=>(a.position||0)-(b.position||0));if(!gallerySnap.empty)gallery=gallerySnap.docs.map(d=>({...d.data(),id:d.id})).sort((a,b)=>(a.position||0)-(b.position||0));}catch(err){console.warn('Konten publik belum dapat disinkronkan:',err);document.getElementById('site-message')?.replaceChildren(document.createTextNode('Konten terbaru belum dapat dimuat. Periksa koneksi internet.'))}render()}
render();load();
