import {doc,collection,getDoc,getDocs,setDoc,deleteDoc} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import {defaults,defaultProducts,safeUrl} from '../site-data.js';
import {uploadDrivePhoto, driveReady} from './drive-photo.js';
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>String(s||'').trim().toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,55);
const field=(name,value,kind='text')=>`<label class="field"><span>${E(name)}</span>${kind==='textarea'?`<textarea data-field="${E(name)}" rows="3">${E(value)}</textarea>`:`<input data-field="${E(name)}" type="${kind}" value="${E(value)}">`}</label>`;
const checkbox=(name,on)=>`<label class="check"><input type="checkbox" data-field="${E(name)}" ${on?'checked':''}> ${E(name)}</label>`;
const v=(el,name)=>{const x=Array.from(el.querySelectorAll('[data-field]')).find(e=>e.dataset.field===name);return x?.type==='checkbox'?!!x.checked:x?.value??''};
const unit=s=>s===''?null:Math.max(0,Math.floor(Number(String(s).replace(/\./g,''))||0));
const button=(label='Simpan & Publikasikan')=>`<div class="form-actions"><button type="submit" class="primary">${E(label)}</button></div>`;
const photo=(label,val)=>`<div class="field"><span>${E(label)}</span>${val?`<img src="${E(val)}" class="cms-photo" alt="${E(label)}">`:''}<input type="file" accept="image/png,image/jpeg,image/webp" data-photo="${E(label)}"><label class="check"><input type="checkbox" data-clear="${E(label)}"> Hapus foto dari halaman</label><small>Foto dikompresi sebelum diunggah ke Google Drive Anda. Firestore hanya menyimpan tautan gambar. Menghapus foto dari halaman tidak menghapus berkas Drive.</small></div>`;
async function compressed(file){
 if(!file)return null;
 if(file.size>15*1024*1024)throw Error('Foto maksimum 15 MB sebelum dikompresi.');
 const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));
 const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));
 canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
 const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.8));
 if(!blob)throw Error('Browser gagal mengolah foto. Gunakan JPG/PNG lain.');
 return blob;
}
async function chosen(form,name,old){
 const el=[...form.querySelectorAll('[data-photo]')].find(x=>x.dataset.photo===name);
 if([...form.querySelectorAll('[data-clear]')].find(x=>x.dataset.clear===name)?.checked)return '';
 if(!el?.files?.length)return old||'';
 if(!driveReady())throw Error('Google Drive belum dikonfigurasi. Ikuti panduan GOOGLE-DRIVE-SETUP.md.');
 const blob=await compressed(el.files[0]);
 const photo=await uploadDrivePhoto(blob,el.files[0].name);
 return photo.url;
}
export async function mountWebsitePublic({container,db,uid,notify}){
let config={...structuredClone(defaults)},products=[],gallery=[],tab='beranda';const cdoc=doc(db,'publicSite','config');
const refresh=async()=>{const [cs,ps,gs]=await Promise.all([getDoc(cdoc),getDocs(collection(db,'publicSite','products')),getDocs(collection(db,'publicSite','gallery'))]);config={...structuredClone(defaults),...(cs.exists()?cs.data():{}),seo:{...defaults.seo,...(cs.exists()?cs.data().seo:{})}};products=ps.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.position||0)-(b.position||0));gallery=gs.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.position||0)-(b.position||0))};
const save=async(upd)=>{const result={...config,...upd};const bytes=new Blob([JSON.stringify(result)]).size;if(bytes>850000)throw Error('Pengaturan terlalu besar. Perkecil foto Beranda/Profil/Logo sebelum menyimpan.');await setDoc(cdoc,result);config=result};
const status=message=>{notify(message);container.querySelector('#pub-status').textContent=message};
const guard=fn=>async e=>{e.preventDefault();const form=e.currentTarget,btn=form.querySelector('[type=submit]');btn.disabled=true;try{await fn(form);status('Perubahan berhasil dipublikasikan.');await refresh();draw()}catch(err){status('Gagal menyimpan: '+err.message);console.error(err)}finally{if(btn.isConnected)btn.disabled=false}};
function generalPanel(){const keys=[['Nama usaha','name'],['Slogan','slogan'],['Copyright footer','copyright'],['Label tombol login','loginLabel'],['Label Beranda','nav.0'],['Label Produk','nav.1'],['Label Galeri','nav.2'],['Label Profil','nav.3'],['Label Kontak','nav.4'],['Judul layanan','serviceTitle'],['Judul ajakan WhatsApp','buttons.whatsapp'],['Label tombol lihat produk','buttons.products'],['Label tombol tanya produk','buttons.productAsk'],['Label tombol bagikan','buttons.share'],['Label tombol Maps','buttons.maps']];return `<div class="card"><h2>Identitas, Navigasi & Footer</h2><p>Link menu tetap menuju halaman yang benar. Semua teks yang terlihat dapat diubah.</p><form id="pub-general" class="form-grid">${keys.map(([l,k])=>field(l,k.startsWith('nav.')?(config.nav||defaults.nav)[Number(k.slice(4))]:k.startsWith('buttons.')?(config.buttons||defaults.buttons)[k.slice(8)]:config[k])).join('')}${photo('Logo website',config.logoImage)}${button()}</form></div>`}
function landingPanel(){return `<div class="card"><h2>Kelola Beranda</h2><p>Harga tidak ditampilkan pada Beranda.</p><form id="pub-landing" class="form-grid">${field('Teks kecil hero',config.heroEyebrow)}${field('Judul utama hero',config.heroTitle)}${field('Deskripsi utama',config.heroText,'textarea')}${photo('Foto utama Beranda',config.heroImage)}${field('Judul bagian Produk',config.homeProductTitle)}${field('Pengantar bagian Produk',config.homeProductIntro,'textarea')}${field('Judul layanan',config.serviceTitle)}${(config.services||[]).map((s,i)=>`<div class="card" style="padding:10px">${field('Layanan '+(i+1)+' judul',s.title)}${field('Layanan '+(i+1)+' deskripsi',s.text)}</div>`).join('')}${button()}</form></div>`}
function productPanel(){return `<div class="card"><h2>Kelola Produk & Harga Publik</h2><p>Harga di sini TERPISAH dari harga modal, FIFO, stok, dan transaksi manajemen telur. Status tersedia/habis diisi manual.</p><form id="pub-catalog">${field('Judul katalog',config.productTitle)}${field('Pengantar katalog',config.productIntro,'textarea')}${field('Catatan harga',config.productNote,'textarea')}${button('Simpan Teks Katalog')}</form><hr><button class="secondary" id="pub-add-prod" type="button">+ Tambah produk publik</button>${!products.length?'<button class="secondary" id="pub-seed" type="button">Buat Produk Awal HORN & OMEGA</button>':''}</div>${products.map(p=>`<div class="card" style="margin-top:12px"><form class="pub-prod" data-id="${E(p.id)}">${field('Nama produk',p.name)}${field('Deskripsi produk',p.description,'textarea')}${field('Harga eceran per kg (Rp)',p.retail??'','number')}${field('Harga grosir per kg (Rp)',p.wholesale??'','number')}${field('Minimum grosir (kg)',p.minWholesale??'','number')}${checkbox('Tampilkan minimum grosir',p.showMin)}${checkbox('Tampilkan produk di website',p.visible!==false)}<label class="field">Status persediaan<select data-field="Status produk"><option value="available" ${p.status!=='out'?'selected':''}>Tersedia</option><option value="out" ${p.status==='out'?'selected':''}>Habis</option></select></label>${field('Urutan produk',p.position||1,'number')}${photo('Foto produk',p.image)}${field('Judul SEO produk',p.seoTitle)}${field('Deskripsi SEO produk',p.seoDescription,'textarea')}${button('Simpan '+p.name)}</form><button class="danger-btn pub-delete-product" data-id="${E(p.id)}">Hapus produk dari website publik</button></div>`).join('')}`}
function galleryPanel(){return `<div class="card"><h2>Foto & Galeri</h2><p>Foto berukuran berbeda akan otomatis menyesuaikan bingkai 1:1; foto besar dapat dibuka saat ditekan.</p><button id="pub-add-gallery" class="secondary" type="button">+ Tambah Foto</button></div>${gallery.map(g=>`<div class="card" style="margin-top:12px"><form class="pub-gallery" data-id="${E(g.id)}">${field('Judul foto',g.title)}${field('Keterangan foto',g.description||'','textarea')}${field('Urutan foto',g.position||1,'number')}${checkbox('Tampilkan foto ini',g.visible!==false)}${photo('Foto galeri',g.image)}${button('Simpan Foto')}</form><button class="danger-btn pub-delete-gallery" data-id="${E(g.id)}">Hapus foto galeri</button></div>`).join('')}`}
function profilePanel(){return `<div class="card"><h2>Kelola Profil Usaha</h2><form id="pub-profile">${field('Judul profil',config.profileTitle)}${field('Deskripsi usaha',config.profileText,'textarea')}${field('Judul sorotan',config.profileHighlightTitle)}${field('Isi sorotan',config.profileHighlightText,'textarea')}${photo('Foto Profil',config.profileImage)}${button()}</form></div>`}
function contactPanel(){return `<div class="card"><h2>Kontak, Lokasi & Multi WhatsApp</h2><p>Satu nomor wajib dipilih sebagai prioritas. Tombol umum, produk, dan tombol mengambang menuju nomor utama. Nomor lain hanya di halaman Kontak.</p><form id="pub-contact">${field('Judul halaman Kontak',config.contactTitle)}${field('Pengantar Kontak',config.contactIntro,'textarea')}${field('Judul lokasi',config.locationTitle)}${field('Alamat usaha',config.address,'textarea')}${field('Wilayah layanan',config.region)}${field('Jam operasional',config.hours,'textarea')}${field('Tautan Google Maps atau URL embed',config.mapsUrl,'url')}${button('Simpan Informasi Kontak')}</form><hr><button id="pub-add-wa" type="button" class="secondary">+ Tambah Nomor WhatsApp</button>${(config.contacts||[]).map((c,i)=>`<form class="pub-wa" data-index="${i}"><div class="card" style="padding:12px;margin-top:12px">${field('Nama kontak',c.name)}${field('Nomor WhatsApp (62...)',c.number,'tel')}${checkbox('Nomor utama / prioritas',!!c.primary)}${checkbox('Tampilkan kontak ini',c.active!==false)}${button('Simpan Kontak')}<button type="button" class="danger-btn pub-delete-wa" data-index="${i}" ${c.primary?'disabled title="Ganti nomor utama dahulu"':''}>Hapus kontak</button></div></form>`).join('')}</div>`}
function seoPanel(){return `<div class="card"><h2>Kelola SEO (Hanya Setelah Login)</h2><p>Prioritas: Cangkang Mas / Cangkangmas serta pencarian umum telur, agen telur, eceran, grosir, HORN, dan OMEGA di Surabaya. Google menentukan kapan dan bagaimana hasil muncul.</p><form id="pub-seo">${Object.entries({beranda:'Beranda',produk:'Produk',galeri:'Galeri',profil:'Profil',kontak:'Kontak'}).map(([key,label])=>`<fieldset style="border:1px solid #dce4ef;border-radius:12px;margin:15px 0"><legend><b>${label}</b></legend>${field(key+' title',config.seo?.[key]?.title||'')}${field(key+' description',config.seo?.[key]?.description||'','textarea')}${checkbox(key+' indeks Google',config.seo?.[key]?.index!==false)}</fieldset>`).join('')}${button('Simpan Pengaturan SEO')}</form><p>SEO produk diatur pada masing-masing produk. Sitemap dan metadata bawaan disiapkan dalam paket ZIP; sebelum domain aktif, jangan mendaftarkannya di Search Console.</p><p><b>Batas GitHub Pages:</b> pengaturan meta SEO di browser dapat dibaca Google saat merender JavaScript, tetapi cuplikan WhatsApp/OG dan sitemap statis tidak langsung berubah mengikuti setiap edit admin. Untuk metadata sosial dan sitemap yang selalu dinamis perlu proses build/publikasi ulang atau hosting dengan rendering server.</p></div>`}
function draw(){container.innerHTML=`<h1 class="page-title">Website Publik</h1><p>Pengaturan website pemasaran Cangkang Mas, terpisah dari data transaksi dan FIFO. Foto diunggah ke Google Drive milik pengelola; jika belum disiapkan, lihat GOOGLE-DRIVE-SETUP.md.</p><p><a class="outline" href="../" target="_blank" rel="noopener">↗ Lihat Website Publik</a></p><div class="tabs" id="pub-tabs">${[['beranda','Beranda'],['produk','Produk & Harga'],['galeri','Galeri'],['profil','Profil'],['kontak','Kontak & WhatsApp'],['identitas','Logo & Footer'],['seo','Kelola SEO']].map(([k,l])=>`<button class="tab ${tab===k?'active':''}" type="button" data-tab="${k}">${l}</button>`).join('')}</div><div id="pub-status" role="status"></div>${({beranda:landingPanel,produk:productPanel,galeri:galleryPanel,profil:profilePanel,kontak:contactPanel,identitas:generalPanel,seo:seoPanel}[tab]||landingPanel)()}`;bind()}
function bind(){container.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;draw()});
const general=container.querySelector('#pub-general');if(general)general.onsubmit=guard(async f=>{const result={...config,nav:[...config.nav],buttons:{...config.buttons}};for(let [k,key] of [['Nama usaha','name'],['Slogan','slogan'],['Copyright footer','copyright'],['Label tombol login','loginLabel'],['Judul layanan','serviceTitle']])result[key]=v(f,k);for(let i=0;i<5;i++)result.nav[i]=v(f,'Label '+['Beranda','Produk','Galeri','Profil','Kontak'][i]);for(let [k,key] of [['Label tombol lihat produk','products'],['Judul ajakan WhatsApp','whatsapp'],['Label tombol tanya produk','productAsk'],['Label tombol bagikan','share'],['Label tombol Maps','maps']])result.buttons[key]=v(f,k);result.logoImage=await chosen(f,'Logo website',config.logoImage);await save(result)});
const landing=container.querySelector('#pub-landing');if(landing)landing.onsubmit=guard(async f=>{await save({heroEyebrow:v(f,'Teks kecil hero'),heroTitle:v(f,'Judul utama hero'),heroText:v(f,'Deskripsi utama'),heroImage:await chosen(f,'Foto utama Beranda',config.heroImage),serviceTitle:v(f,'Judul layanan'),homeProductTitle:v(f,'Judul bagian Produk'),homeProductIntro:v(f,'Pengantar bagian Produk'),services:(config.services||[]).map((s,i)=>({title:v(f,'Layanan '+(i+1)+' judul'),text:v(f,'Layanan '+(i+1)+' deskripsi')}))})});
const catalog=container.querySelector('#pub-catalog');if(catalog)catalog.onsubmit=guard(async f=>save({productTitle:v(f,'Judul katalog'),productIntro:v(f,'Pengantar katalog'),productNote:v(f,'Catatan harga')}));
const profile=container.querySelector('#pub-profile');if(profile)profile.onsubmit=guard(async f=>save({profileTitle:v(f,'Judul profil'),profileText:v(f,'Deskripsi usaha'),profileHighlightTitle:v(f,'Judul sorotan'),profileHighlightText:v(f,'Isi sorotan'),profileImage:await chosen(f,'Foto Profil',config.profileImage)}));
const contact=container.querySelector('#pub-contact');if(contact)contact.onsubmit=guard(async f=>{const m=v(f,'Tautan Google Maps atau URL embed');if(m&&!safeUrl(m))throw Error('Tautan Maps harus dimulai dengan https://');await save({contactTitle:v(f,'Judul halaman Kontak'),contactIntro:v(f,'Pengantar Kontak'),locationTitle:v(f,'Judul lokasi'),address:v(f,'Alamat usaha'),region:v(f,'Wilayah layanan'),hours:v(f,'Jam operasional'),mapsUrl:m})});
const seo=container.querySelector('#pub-seo');if(seo)seo.onsubmit=guard(async f=>{const newSEO={...config.seo};for(let k of ['beranda','produk','galeri','profil','kontak'])newSEO[k]={title:v(f,k+' title'),description:v(f,k+' description'),index:v(f,k+' indeks Google')};await save({seo:newSEO})});
container.querySelector('#pub-seed')?.addEventListener('click',async()=>{try{for(const p of defaultProducts){const {id,...data}=p;await setDoc(doc(db,'publicSite','products',id),data)}await refresh();draw();status('HORN dan OMEGA dibuat. Isi harga publik sebelum membagikan website.')}catch(e){status('Gagal: '+e.message)}});
container.querySelector('#pub-add-prod')?.addEventListener('click',async()=>{const name=prompt('Nama produk publik baru:');if(!name)return;const id=slug(name);if(!id||products.some(p=>p.id===id))return status('Nama produk sudah ada atau tidak valid.');try{await setDoc(doc(db,'publicSite','products',id),{name,description:'',retail:null,wholesale:null,minWholesale:null,showMin:false,status:'available',visible:true,position:products.length+1,image:'',seoTitle:name+' | Cangkang Mas',seoDescription:name+' dari Cangkang Mas Surabaya.'});await refresh();draw()}catch(e){status('Gagal: '+e.message)}});
container.querySelectorAll('.pub-prod').forEach(f=>f.onsubmit=guard(async form=>{const id=form.dataset.id,old=products.find(p=>p.id===id);if(!old)throw Error('Produk tidak ditemukan.');const image=await chosen(form,'Foto produk',old.image);const result={name:v(form,'Nama produk'),description:v(form,'Deskripsi produk'),retail:unit(v(form,'Harga eceran per kg (Rp)')),wholesale:unit(v(form,'Harga grosir per kg (Rp)')),minWholesale:unit(v(form,'Minimum grosir (kg)')),showMin:v(form,'Tampilkan minimum grosir'),visible:v(form,'Tampilkan produk di website'),status:v(form,'Status produk'),position:Number(v(form,'Urutan produk'))||1,image,seoTitle:v(form,'Judul SEO produk'),seoDescription:v(form,'Deskripsi SEO produk')};if(!result.name.trim())throw Error('Nama produk wajib diisi.');if(new Blob([JSON.stringify(result)]).size>850000)throw Error('Foto produk terlalu besar.');await setDoc(doc(db,'publicSite','products',id),result)}));
container.querySelectorAll('.pub-delete-product').forEach(b=>b.onclick=async()=>{if(!confirm('Hapus produk dari WEBSITE PUBLIK? Produk internal manajemen telur tidak berubah.'))return;try{await deleteDoc(doc(db,'publicSite','products',b.dataset.id));await refresh();draw();status('Produk publik dihapus.')}catch(e){status('Gagal: '+e.message)}});
container.querySelector('#pub-add-gallery')?.addEventListener('click',async()=>{const id='foto-'+Date.now();try{await setDoc(doc(db,'publicSite','gallery',id),{title:'Foto baru',description:'',position:gallery.length+1,visible:true,image:''});await refresh();draw()}catch(e){status('Gagal: '+e.message)}});
container.querySelectorAll('.pub-gallery').forEach(f=>f.onsubmit=guard(async form=>{const id=form.dataset.id,old=gallery.find(g=>g.id===id);const result={title:v(form,'Judul foto'),description:v(form,'Keterangan foto'),position:Number(v(form,'Urutan foto'))||1,visible:v(form,'Tampilkan foto ini'),image:await chosen(form,'Foto galeri',old?.image)};await setDoc(doc(db,'publicSite','gallery',id),result)}));
container.querySelectorAll('.pub-delete-gallery').forEach(b=>b.onclick=async()=>{if(!confirm('Hapus foto publik ini?'))return;try{await deleteDoc(doc(db,'publicSite','gallery',b.dataset.id));await refresh();draw();status('Foto galeri dihapus.')}catch(e){status('Gagal: '+e.message)}});
container.querySelector('#pub-add-wa')?.addEventListener('click',async()=>{const c=[...(config.contacts||[])];c.push({name:'WhatsApp Alternatif '+(c.length+1),number:'',primary:!c.length,active:true});try{await save({contacts:c});draw()}catch(e){status('Gagal: '+e.message)}});
container.querySelectorAll('.pub-wa').forEach(f=>f.onsubmit=guard(async form=>{const i=Number(form.dataset.index),all=[...(config.contacts||[])],number=v(form,'Nomor WhatsApp (62...)').replace(/\D/g,'');if(number&&!/^(62|0)[0-9]{8,14}$/.test(number))throw Error('Masukkan nomor WA dengan awalan 62 atau 0.');const main=v(form,'Nomor utama / prioritas');if(main&&!number)throw Error('Nomor utama tidak boleh kosong.');all[i]={name:v(form,'Nama kontak'),number,primary:main,active:main?true:v(form,'Tampilkan kontak ini')};if(main)all.forEach((c,j)=>{if(j!==i)c.primary=false});if(!all.some(c=>c.primary&&c.active&&c.number))throw Error('Minimal satu nomor utama yang aktif harus tersedia.');await save({contacts:all})}));
container.querySelectorAll('.pub-delete-wa').forEach(b=>b.onclick=async()=>{const i=Number(b.dataset.index),all=[...(config.contacts||[])];if(all[i]?.primary)return;if(!confirm('Hapus nomor WhatsApp alternatif?'))return;all.splice(i,1);try{await save({contacts:all});draw()}catch(e){status('Gagal: '+e.message)}});
}
container.textContent='Memuat pengaturan Website Publik…';try{await refresh();draw()}catch(err){container.textContent='Gagal membuka pengaturan Website Publik: '+err.message;notify(err.message,true)}
}
